Update 1.20.1 to SVC 1.5.13
henkelmax/replay-voice-chat pull request #33
Opened 2024-05-06 18:30 UTC by ByThePowerOfScience

This tiny change allows the 1.20.1 version to function on the latest release of Simple Voice Chat.

Since 1.20.1 of SVC is still in active development and a lot of modpacks have already been created for 1.20.1, it sadly can't really be considered an "outdated" version quite yet.

I hate maintaining old versions as much as the next guy, but this could actually be simplified substantially.  Since the mod dependencies stay absolutely constant across versions, it wouldn't be too difficult to use a completely MC-version agnostic build.  I could even refactor the project for you if you want.

2024-05-06 20:18 UTC, henkelmax requested changes

2024-05-06 20:18 UTC, henkelmax commented on build.gradle
> +        url 'https://cursemaven.com'
Is there a reason, this was added?

2024-05-06 20:18 UTC, henkelmax commented on gradle.properties
> +voicechat_api_version=2.5.0
What did you change, so the API needs 2.5?

2024-05-06 20:18 UTC, henkelmax commented on gradle/wrapper/gradle-wrapper.properties
> +distributionUrl=https\://services.gradle.org/distributions/gradle-8.6-bin.zip
Just changing the gradle distribution URL won't properly upgrade gradle.

2024-05-07 00:47 UTC, ByThePowerOfScience commented on build.gradle
> +    id 'fabric-loom' version '1.6.11'
It's best practice not to depend on a changing version.

2024-05-07 00:48 UTC, ByThePowerOfScience commented on build.gradle
> +tasks.modrinth.dependsOn(build)
I don't think I did? Weird.

2024-05-07 07:21 UTC, henkelmax commented on build.gradle
> +    id 'fabric-loom' version '1.6.11'
That's not true, even Fabric themselves don't depend on exact patch versions:
https://github.com/FabricMC/fabric-example-mod/blob/2930d654410f005963a3c695860a3f5ca93d60d7/build.gradle#L2

2024-05-07 07:37 UTC, closed without merging

2024-05-07 09:32 UTC, ByThePowerOfScience commented on build.gradle
> +    id 'fabric-loom' version '1.6.11'
Fair, and you don't have to add that change specifically if you don't want to.